const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const WebSocket=require('ws');
const {Pool}=require('pg');
const PORT=Number(process.env.PORT||3000),HOST='0.0.0.0',PUBLIC=path.join(__dirname,'public');
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false}):null;
let mem={users:[],messages:[],groups:[],groupMessages:[]};

function hashPassword(password){const salt=crypto.randomBytes(16).toString('hex');const hash=crypto.scryptSync(String(password),salt,64).toString('hex');return `${salt}:${hash}`}
function verifyPassword(password,stored){if(!stored||!stored.includes(':'))return false;const [salt,hex]=stored.split(':');try{const a=Buffer.from(hex,'hex'),b=Buffer.from(crypto.scryptSync(String(password),salt,64));return a.length===b.length&&crypto.timingSafeEqual(a,b)}catch{return false}}

async function init(){
 if(!pool){console.log('DATABASE_URL not set: using temporary memory store');return}
 await pool.query(`
 CREATE TABLE IF NOT EXISTS users(id text PRIMARY KEY,username text UNIQUE NOT NULL,display_name text NOT NULL,avatar text DEFAULT '',friends jsonb DEFAULT '[]',created_at bigint NOT NULL);
 CREATE TABLE IF NOT EXISTS messages(id text PRIMARY KEY,"from" text NOT NULL,"to" text NOT NULL,text text NOT NULL,time bigint NOT NULL);
 CREATE TABLE IF NOT EXISTS groups_data(id text PRIMARY KEY,name text NOT NULL,owner text NOT NULL,members jsonb DEFAULT '[]',created_at bigint NOT NULL);
 CREATE TABLE IF NOT EXISTS group_messages(id text PRIMARY KEY,group_id text NOT NULL,"from" text NOT NULL,text text NOT NULL,time bigint NOT NULL);
 ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash text DEFAULT '';
 ALTER TABLE groups_data ADD COLUMN IF NOT EXISTS username text;
 ALTER TABLE groups_data ADD COLUMN IF NOT EXISTS avatar text DEFAULT '';
 UPDATE groups_data SET username=lower(regexp_replace(name,'[^a-zA-Z0-9_.-]','','g'))||'group' WHERE username IS NULL OR username='';
 `);
 console.log('Database ready')
}
const clean=u=>({id:u.id,username:u.username,displayName:u.display_name||u.displayName||u.username,avatar:u.avatar||'',friends:Array.isArray(u.friends)?u.friends:[],createdAt:Number(u.created_at||u.createdAt||Date.now())});
async function users(){if(!pool)return mem.users.map(clean);const r=await pool.query('SELECT * FROM users ORDER BY created_at ASC');return r.rows.map(clean)}
async function findUser(username){username=String(username||'').toLowerCase();if(!pool)return mem.users.find(u=>u.username===username);const r=await pool.query('SELECT * FROM users WHERE username=$1',[username]);return r.rows[0]&&clean(r.rows[0])}
async function rawUser(username){username=String(username||'').toLowerCase();if(!pool)return mem.users.find(u=>u.username===username);const r=await pool.query('SELECT * FROM users WHERE username=$1',[username]);return r.rows[0]}
async function deleteAccount(username){
 username=String(username||'').toLowerCase();
 if(!pool){mem.messages=mem.messages.filter(m=>m.from!==username&&m.to!==username);mem.groupMessages=mem.groupMessages.filter(m=>m.from!==username);mem.groups=mem.groups.filter(g=>g.owner!==username);mem.groups.forEach(g=>g.members=(g.members||[]).filter(x=>x!==username));mem.users.forEach(u=>u.friends=(u.friends||[]).filter(x=>x!==username));mem.users=mem.users.filter(u=>u.username!==username);return}
 await pool.query('DELETE FROM messages WHERE "from"=$1 OR "to"=$1',[username]);
 await pool.query('DELETE FROM group_messages WHERE "from"=$1',[username]);
 await pool.query('DELETE FROM groups_data WHERE owner=$1',[username]);
 await pool.query("UPDATE groups_data SET members=(SELECT COALESCE(jsonb_agg(x),'[]'::jsonb) FROM jsonb_array_elements(members) x WHERE x #>> '{}' <> $1) WHERE members ? $1",[username]);
 await pool.query("UPDATE users SET friends=(SELECT COALESCE(jsonb_agg(x),'[]'::jsonb) FROM jsonb_array_elements(friends) x WHERE x #>> '{}' <> $1) WHERE friends ? $1",[username]);
 await pool.query('DELETE FROM users WHERE username=$1',[username]);
}
async function createUser(username,password){const u={id:crypto.randomUUID(),username,displayName:username,avatar:'',friends:[],createdAt:Date.now(),passwordHash:hashPassword(password)};if(!pool){mem.users.push(u);return clean(u)}const r=await pool.query('INSERT INTO users(id,username,display_name,avatar,friends,created_at,password_hash) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[u.id,u.username,u.displayName,u.avatar,JSON.stringify(u.friends),u.createdAt,u.passwordHash]);return clean(r.rows[0])}
async function setPassword(username,password){const h=hashPassword(password);if(!pool){const u=mem.users.find(x=>x.username===username);if(u)u.passwordHash=h;return}await pool.query('UPDATE users SET password_hash=$1 WHERE username=$2',[h,username])}
async function updateAvatar(username,avatar){if(!pool){const u=mem.users.find(x=>x.username===username);if(u)u.avatar=avatar;return}await pool.query('UPDATE users SET avatar=$1 WHERE username=$2',[avatar,username])}
async function updateFriends(username,friends){if(!pool){const u=mem.users.find(x=>x.username===username);if(u)u.friends=friends;return}await pool.query('UPDATE users SET friends=$1 WHERE username=$2',[JSON.stringify(friends),username])}
async function allMessages(){if(!pool)return mem.messages;const r=await pool.query('SELECT id,"from","to",text,time FROM messages ORDER BY time ASC');return r.rows.map(x=>({...x,time:Number(x.time)}))}
async function addMessage(m){if(!pool){mem.messages.push(m);return}await pool.query('INSERT INTO messages(id,"from","to",text,time) VALUES($1,$2,$3,$4,$5)',[m.id,m.from,m.to,m.text,m.time])}
async function clearMessages(a,b){if(!pool){mem.messages=mem.messages.filter(m=>!((m.from===a&&m.to===b)||(m.from===b&&m.to===a)));return}await pool.query('DELETE FROM messages WHERE ("from"=$1 AND "to"=$2) OR ("from"=$2 AND "to"=$1)',[a,b])}
async function allGroups(){if(!pool)return mem.groups;const r=await pool.query('SELECT * FROM groups_data ORDER BY created_at ASC');return r.rows.map(x=>({id:x.id,name:x.name,username:x.username||'',owner:x.owner,members:Array.isArray(x.members)?x.members:[],avatar:x.avatar||'',createdAt:Number(x.created_at)}))}
async function findGroupByUsername(username){username=String(username||'').replace(/^@/,'').trim().toLowerCase();if(!pool)return mem.groups.find(g=>g.username===username);const r=await pool.query('SELECT * FROM groups_data WHERE lower(username)=lower($1) LIMIT 1',[username]);return r.rows[0]&&{id:r.rows[0].id,name:r.rows[0].name,username:r.rows[0].username||'',owner:r.rows[0].owner,members:Array.isArray(r.rows[0].members)?r.rows[0].members:[],avatar:r.rows[0].avatar||'',createdAt:Number(r.rows[0].created_at)}}
async function addGroup(g){if(!pool){mem.groups.push(g);return}await pool.query('INSERT INTO groups_data(id,name,username,owner,members,avatar,created_at) VALUES($1,$2,$3,$4,$5,$6,$7)',[g.id,g.name,g.username,g.owner,JSON.stringify(g.members),g.avatar||'',g.createdAt])}
async function updateGroup(g){if(!pool){const i=mem.groups.findIndex(x=>x.id===g.id);if(i>=0)mem.groups[i]=g;return}await pool.query('UPDATE groups_data SET name=$1,username=$2,members=$3,avatar=$4 WHERE id=$5',[g.name,g.username,JSON.stringify(g.members),g.avatar||'',g.id])}
async function deleteGroup(id){if(!pool){mem.groupMessages=mem.groupMessages.filter(m=>m.groupId!==id);mem.groups=mem.groups.filter(g=>g.id!==id);return}await pool.query('DELETE FROM group_messages WHERE group_id=$1',[id]);await pool.query('DELETE FROM groups_data WHERE id=$1',[id])}
async function allGroupMessages(){if(!pool)return mem.groupMessages;const r=await pool.query('SELECT id,group_id,"from",text,time FROM group_messages ORDER BY time ASC');return r.rows.map(x=>({...x,groupId:x.group_id,time:Number(x.time)}))}
async function addGroupMessage(m){if(!pool){mem.groupMessages.push(m);return}await pool.query('INSERT INTO group_messages(id,group_id,"from",text,time) VALUES($1,$2,$3,$4,$5)',[m.id,m.groupId,m.from,m.text,m.time])}
async function clearGroupMessages(id){if(!pool){mem.groupMessages=mem.groupMessages.filter(m=>m.groupId!==id);return}await pool.query('DELETE FROM group_messages WHERE group_id=$1',[id])}
function json(res,status,obj){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Cache-Control':'no-store'});res.end(JSON.stringify(obj))}
function body(req){return new Promise((resolve,reject)=>{let d='';req.on('data',c=>{d+=c;if(d.length>2e6){req.destroy();reject(new Error('too large'))}});req.on('end',()=>{try{resolve(d?JSON.parse(d):{})}catch(e){reject(e)}});req.on('error',reject)})}
async function ai(message){const key=process.env.OPENROUTER_API_KEY||process.env.AI_API_KEY;if(!key)return 'neXi AI сейчас не подключён. Администратору нужно добавить OPENROUTER_API_KEY в Environment Variables Render.';const base=(process.env.AI_BASE_URL||'https://openrouter.ai/api/v1').replace(/\/$/,'');const model=process.env.AI_MODEL||'openrouter/free';const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);try{const r=await fetch(base+'/chat/completions',{method:'POST',headers:{'Authorization':'Bearer '+key,'Content-Type':'application/json','X-Title':'craTe.'},body:JSON.stringify({model,messages:[{role:'system',content:'Ты neXi AI — встроенный дружелюбный AI-помощник мессенджера craTe. Отвечай на русском, если пользователь пишет по-русски. Отвечай полезно и естественно.'},{role:'user',content:message}],temperature:.7,max_tokens:800}),signal:controller.signal});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.error?.message||('AI HTTP '+r.status));const reply=data?.choices?.[0]?.message?.content;if(!reply)throw new Error('AI returned empty response');return String(reply).trim()}catch(e){console.error('AI error:',e.message);return 'neXi AI временно не смог ответить. Попробуй ещё раз через несколько секунд.'}finally{clearTimeout(timer)}}
const server=http.createServer(async(req,res)=>{try{
 if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type'});return res.end()}
 if(req.url==='/api/health')return json(res,200,{ok:true,name:'craTe.'});
 if(req.url.startsWith('/api/users/check/')){const username=decodeURIComponent(req.url.slice('/api/users/check/'.length)).replace(/^@/,'').trim().toLowerCase();const valid=/^[a-z0-9_.-]{3,24}$/.test(username);const exists=valid?!!(await findUser(username)):false;return json(res,200,{available:valid&&!exists,valid})}
 if(req.url==='/api/register'&&req.method==='POST'){const b=await body(req),username=String(b.username||'').replace(/^@/,'').trim().toLowerCase(),password=String(b.password||'');if(!/^[a-z0-9_.-]{3,24}$/.test(username))return json(res,400,{error:'Username: 3–24 символа, только a-z, 0-9, _, ., -'});if(password.length<6)return json(res,400,{error:'Пароль должен быть минимум 6 символов'});if(await findUser(username))return json(res,409,{error:'Username уже занят'});return json(res,201,{user:await createUser(username,password)})}
 if(req.url==='/api/login'&&req.method==='POST'){const b=await body(req),username=String(b.username||'').replace(/^@/,'').trim().toLowerCase(),password=String(b.password||'');if(password.length<6)return json(res,400,{error:'Введи пароль минимум 6 символов'});const raw=await rawUser(username);if(!raw)return json(res,404,{error:'Пользователь не найден'});if(!raw.password_hash){await setPassword(username,password)}else if(!verifyPassword(password,raw.password_hash))return json(res,401,{error:'Неверный пароль'});return json(res,200,{user:await findUser(username)})}
 if(req.url==='/api/delete-account'&&req.method==='POST'){const b=await body(req),username=String(b.username||'').replace(/^@/,'').trim().toLowerCase(),password=String(b.password||'');const raw=await rawUser(username);if(!raw)return json(res,404,{error:'Пользователь не найден'});if(raw.password_hash&&!verifyPassword(password,raw.password_hash))return json(res,401,{error:'Неверный пароль'});await deleteAccount(username);for(const [x,u] of clients){if(u.username===username&&x.readyState===WebSocket.OPEN)x.send(JSON.stringify({type:'account-deleted',username}))}return json(res,200,{ok:true})}
 if(req.url==='/api/avatar'&&req.method==='POST'){const b=await body(req),username=String(b.username||'').replace(/^@/,'').trim().toLowerCase(),avatar=String(b.avatar||'');if(!username||avatar.length>1500000)return json(res,400,{error:'Некорректный аватар'});const raw=await rawUser(username);if(!raw)return json(res,404,{error:'Пользователь не найден'});await updateAvatar(username,avatar);return json(res,200,{ok:true})}
 if(req.url==='/api/users'&&req.method==='GET')return json(res,200,{users:await users()});
 if(req.url==='/api/snapshot')return json(res,200,{users:await users(),messages:await allMessages(),groups:await allGroups(),groupMessages:await allGroupMessages()});
 if(req.url==='/api/ai'&&req.method==='POST'){const b=await body(req),message=String(b.message||'').trim();if(!message)return json(res,400,{error:'Пустое сообщение'});return json(res,200,{reply:await ai(message)})}
 let file=req.url==='/'?'/index.html':req.url.split('?')[0];const fp=path.normalize(path.join(PUBLIC,file));if(!fp.startsWith(PUBLIC))return json(res,403,{error:'forbidden'});return fs.readFile(fp,(err,data)=>{if(err){res.writeHead(404);return res.end('Not found')}const ext=path.extname(fp).toLowerCase(),ct={'.html':'text/html; charset=utf-8','.js':'application/javascript','.css':'text/css','.mp3':'audio/mpeg','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.woff2':'font/woff2','.woff':'font/woff','.ttf':'font/ttf','.otf':'font/otf'}[ext]||'application/octet-stream';res.writeHead(200,{'Content-Type':ct,'Cache-Control':'no-cache'});res.end(data)})
 }catch(e){console.error('HTTP error:',e);if(!res.headersSent)json(res,500,{error:'Server error'})}});
const wss=new WebSocket.Server({server}),clients=new Map();
function sendTo(username,obj){for(const [ws,u] of clients)if(u.username===username&&ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify(obj))}
function online(){return [...clients.values()].map(u=>u.username)}
async function snapshot(){return {users:await users(),messages:await allMessages(),groups:await allGroups(),groupMessages:await allGroupMessages()}}
function groupPublic(g){return {id:g.id,name:g.name,username:g.username,owner:g.owner,members:g.members||[],avatar:g.avatar||'',createdAt:g.createdAt}}

wss.on('connection',ws=>{ws.isAlive=true;ws.on('pong',()=>ws.isAlive=true);ws.on('message',async raw=>{try{const m=JSON.parse(raw);if(m.type==='ping')return;
 if(m.type==='hello'&&m.user){const real=await findUser(m.user.username);if(!real)return;ws.user=real;clients.set(ws,ws.user);ws.send(JSON.stringify({type:'snapshot',...(await snapshot()),online:online()}));for(const [x] of clients)if(x!==ws&&x.readyState===WebSocket.OPEN)x.send(JSON.stringify({type:'presence',username:ws.user.username,online:true}));return}
 if(!ws.user)return;
 if(m.type==='avatar-update'){const avatar=String(m.avatar||'');if(avatar.length>1500000)return ws.send(JSON.stringify({type:'error',message:'Слишком большой аватар'}));await updateAvatar(ws.user.username,avatar);ws.user={...ws.user,avatar};for(const [x] of clients)if(x.readyState===WebSocket.OPEN)x.send(JSON.stringify({type:'avatar-updated',username:ws.user.username,avatar}));return}
 if(m.type==='add-friend'){const target=String(m.username||'').replace(/^@/,'').trim().toLowerCase();if(!target||target===ws.user.username)return;const other=await findUser(target);if(!other)return ws.send(JSON.stringify({type:'error',message:'Пользователь не найден'}));const me=await findUser(ws.user.username);const mf=[...(me.friends||[])],of=[...(other.friends||[])];if(!mf.includes(target))mf.push(target);if(!of.includes(me.username))of.push(me.username);await updateFriends(me.username,mf);await updateFriends(other.username,of);ws.user={...me,friends:mf};sendTo(me.username,{type:'friends',friends:mf});sendTo(target,{type:'friends',friends:of});return}
 if(m.type==='message'){const to=String(m.to||'').replace(/^@/,'').trim().toLowerCase(),text=String(m.text||'').trim().slice(0,4000);if(!to||!text)return;const me=await findUser(ws.user.username);if(!(me.friends||[]).includes(to))return ws.send(JSON.stringify({type:'error',message:'Сначала добавь пользователя в друзья'}));const msg={id:crypto.randomUUID(),from:ws.user.username,to,text,time:Date.now()};await addMessage(msg);sendTo(to,{type:'message',message:msg});ws.send(JSON.stringify({type:'message',message:msg}));return}
 if(m.type==='clear-chat'){const to=String(m.to||'').replace(/^@/,'').trim().toLowerCase();if(!to)return;await clearMessages(ws.user.username,to);sendTo(to,{type:'clear-chat',username:ws.user.username});ws.send(JSON.stringify({type:'clear-chat',username:ws.user.username}));return}
 if(m.type==='group-create'){const name=String(m.name||'').trim().slice(0,50),username=String(m.username||'').replace(/^@/,'').trim().toLowerCase(),avatar=String(m.avatar||'');if(!name||!/^[a-z0-9_.-]*group$/.test(username))return ws.send(JSON.stringify({type:'error',message:'Username группы должен заканчиваться group'}));if(avatar.length>1500000)return ws.send(JSON.stringify({type:'error',message:'Слишком большой аватар'}));if(await findGroupByUsername(username))return ws.send(JSON.stringify({type:'error',message:'Этот username группы уже занят'}));const g={id:crypto.randomUUID(),name,username,owner:ws.user.username,members:[ws.user.username],avatar,createdAt:Date.now()};await addGroup(g);for(const [x] of clients)if(x.readyState===WebSocket.OPEN)x.send(JSON.stringify({type:'group',group:groupPublic(g)}));return}
 if(m.type==='group-join'){const gs=await allGroups(),g=gs.find(x=>x.id===m.groupId);if(!g)return ws.send(JSON.stringify({type:'error',message:'Группа не найдена'}));if(!(g.members||[]).includes(ws.user.username))g.members=[...(g.members||[]),ws.user.username];await updateGroup(g);for(const [x] of clients)if(x.readyState===WebSocket.OPEN)x.send(JSON.stringify({type:'group-joined',group:groupPublic(g)}));return}
 if(m.type==='group-message'){const id=String(m.groupId||''),text=String(m.text||'').trim().slice(0,4000);if(!id||!text)return;const gs=await allGroups(),g=gs.find(x=>x.id===id);if(!g)return ws.send(JSON.stringify({type:'error',message:'Группа не найдена'}));const msg={id:crypto.randomUUID(),groupId:id,from:ws.user.username,text,time:Date.now()};await addGroupMessage(msg);for(const [x] of clients)if(x.readyState===WebSocket.OPEN)x.send(JSON.stringify({type:'group-message',message:msg}));return}
 if(m.type==='group-clear'){const id=String(m.groupId||''),g=(await allGroups()).find(x=>x.id===id);if(!g)return ws.send(JSON.stringify({type:'error',message:'Группа не найдена'}));await clearGroupMessages(id);for(const [x] of clients)if(x.readyState===WebSocket.OPEN)x.send(JSON.stringify({type:'group-clear',groupId:id}));return}
 if(m.type==='group-delete'){const id=String(m.groupId||''),g=(await allGroups()).find(x=>x.id===id);if(!g)return ws.send(JSON.stringify({type:'error',message:'Группа не найдена'}));if(g.owner!==ws.user.username)return ws.send(JSON.stringify({type:'error',message:'Удалить группу может только владелец'}));await deleteGroup(id);for(const [x] of clients)if(x.readyState===WebSocket.OPEN)x.send(JSON.stringify({type:'group-deleted',groupId:id}));return}
 if(['call-offer','call-answer','ice','call-end'].includes(m.type)&&m.to)sendTo(String(m.to).replace(/^@/,'').toLowerCase(),{...m,from:ws.user.username});
 }catch(e){console.error('WS error:',e);try{ws.send(JSON.stringify({type:'error',message:'Ошибка сервера'}))}catch{}}});
 ws.on('close',()=>{const u=clients.get(ws);clients.delete(ws);if(u)for(const [x] of clients)if(x.readyState===WebSocket.OPEN)x.send(JSON.stringify({type:'presence',username:u.username,online:false}))})
});
setInterval(()=>{for(const ws of wss.clients){if(!ws.isAlive){ws.terminate();continue}ws.isAlive=false;ws.ping()}},30000);
init().then(()=>server.listen(PORT,HOST,()=>console.log(`craTe. listening on ${PORT}`))).catch(e=>{console.error('Startup error',e);process.exit(1)});
